--- 
title: "会計情報のデータ分析"
site: bookdown::bookdown_site
output: bookdown::gitbook
---

最終更新日：`r format(Sys.Date(), "%Y/%m/%d")`

　近年，会計データを用いた経営分析は，単なる比率の分析だけでなく，計量経済学の知見を取り入れて発展してきた。本書は，このような統計的な技法を含めた会計データ分析の入門書である。このような分析に必要となるのは，

- 会計学の知識
- 統計学の知識
- 統計ソフトの知識

である。本書は，会計学の知識については，日商簿記検定の3級程度，統計学や統計ソフトの知識はほとんどないという学部生を対象として執筆された。入門書であるが，データの整形作業などのデータ分析の必要な工程は最低限網羅している。本書の演習を通じて，会計データ分析の世界へ第一歩を生み出してほしい。

著者一同


## 目次 {-}
- 第0章 会計情報を統計分析する：必要性と困難性
- 第1章 会計データへのアクセス
- 第2章 会計情報を前処理する（基礎）
- 第3章 会計情報を前処理する（応用）　
- 第4章 会計情報の可視化
- 第5章 会計情報を検定する
- 第6章 単回帰分析とCVP分析
- 第7章 コスト・ビヘイビア推定する

## 編集者情報 {-}
50音順，所属・職位は2020年4月1日時点，名前のリンクは[researchmap](https://researchmap.jp)

- [新井康平](https://researchmap.jp/read0141082)　大阪府立大学現代システム科学域マネジメント学類/経済学研究科 准教授　[HP](https://sites.google.com/view/arailab/)
  - 第0章執筆，問題作成
- [井上謙仁](https://researchmap.jp/kinoue9319)　近畿大学経営学部 特任講師
  - 第1章，第3章執筆
- [小笠原享](https://researchmap.jp/togasawara)　熊本学園大学商学部 講師
  - 第2章執筆，第3章執筆，第4章執筆，第7章執筆
- [北田智久](https://researchmap.jp/ktd/)　近畿大学経営学部 講師
  - 編集，第1章，第6章執筆
- [濵村純平](https://researchmap.jp/jmhama)　桃山学院大学経営学部 講師　[HP](https://sites.google.com/site/bincunchunpingnohomupeji/home)
  - 編集
- 早川　翔　流通科学大学商学部 講師
  - 第5章執筆
- 吉田政之　尾道市立大学経済情報学部
  - 第3章，第5章執筆

